FROM docker.io/rockylinux/rockylinux:10-ubi-init

ENV container=podman

# The UBI-init image already has systemd configured
# Just install Python and basic utilities for Ansible
RUN dnf -y install \
    python3 python3-pip sudo bash iproute \
    && dnf clean all

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
